### ISSUE TITLE
YamlDotNet序列化的yaml无法读取

### ISSUE THREAD

**Issue by lycc193** [mamoe/mirai-console#277]
AutoLogin.yaml 默认的（kt?）结构是这样的
```
accounts: 
  - account: 123456
    password: 
      kind: PLAIN
      value: pwd
    configuration: {}
```

在我使用C#和YamlDotNet 反序列化 -> 修改参数 -> 序列化 之后 结构变成了如下
```
accounts:
- account: 123456
  password:
    kind: PLAIN
    value: pwd
  configuration: {}
```

重新序列化之后的结构 mirai无法读取，并报错 重置了配置文件

YamlDotNet读取的序列化前后的结构均为`Directory<object,List<Directory<object,object>>>`
通过一些在线校验的网站测试，这两个结构也是等价的

所以，是YamlDotNet的问题吗，或者 我的操作有问题吗，如果是 有mirai可用的C# yaml库吗
