### ISSUE TITLE
单一配置文件

### ISSUE THREAD

**Issue by copydog** [mamoe/mirai-console#38]
建议采用单一配置文件，这样插件之间更方便相互获取配置文件

```yaml
MiraiApiHttp:
  port: 8080
  authKey: 1234567890
  cacheSize: 4096
  enableWebsocket: false
  cors:
    - '*'

MiraiAdminClient:
  account: 775150
  domain: localhost
  identifier: 775150-default
  heartBeat: 15000

OtherPlugin:
  foo: bar

```

如果觉得可以，我等下pr
